"""
evaluate_learned.py -- how much headroom would LEARNED weights buy?

Imran's "consider more advanced modelling" + Sauvik's "keep validating the
weights", answered with one experiment: train a logistic regression and a
gradient-boosted model to predict purchase from the SAME censored features
the rule engine sees, on the SAME train windows, and compare ranking power
on the SAME held-out data and samples as reports/baseline-comparison.md.

If the learned models barely beat the interpretable engine, the MVP's
weighting is close to what the features support and the roadmap models are
optional polish. If they beat it soundly, we know the size of the prize and
where it lives (feature importances tell us which signal the rules underuse).

Fairness notes
--------------
* Both policies see the identical feature set, including added_to_cart /
  views_before_first_commercial (the engine's Decisive trigger).
* Engine ranking score = intent tier, confidence as tie-break (exactly the
  ranking used in the baseline concentration tables).
* Temporal split, censored features, fixed seeds throughout.

Writes reports/learned-weights-headroom.md.
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

from intent_engine import REAL_INTENTS, TwoStageEngine

SPLIT_MS = 1439856000000
SEED = 42
REES_TRAIN_SAMPLE = 2_000_000
REES_TEST_SAMPLE = 500_000
CUTS = [0.05, 0.10, 0.20]
TIER = {"Decisive": 5, "Evaluator": 4, "Explorer": 3, "Unclear": 2, "Low-intent": 1}

BASE_FEATS = ["n_events", "n_views", "revisit_ratio", "n_categories",
              "top_category_share", "category_switch_rate", "median_gap_sec",
              "duration_sec", "price_rel_cat"]
MODEL_FEATS = BASE_FEATS + ["views_before_first_commercial", "added_to_cart"]
NEUTRAL = {"revisit_ratio": 1.0, "top_category_share": 0.0,
           "category_switch_rate": 0.0, "median_gap_sec": 0.0,
           "duration_sec": 0.0, "n_categories": 0.0, "n_events": 0.0,
           "n_views": 0.0, "price_rel_cat": 1.0,
           "views_before_first_commercial": 0.0}


def matrix(df):
    X = df.reindex(columns=MODEL_FEATS).copy()
    X["added_to_cart"] = X["added_to_cart"].astype(float)
    # division artifacts (e.g. revisit_ratio with 0 unique items) -> neutral
    X = X.replace([np.inf, -np.inf], np.nan)
    for c, v in NEUTRAL.items():
        X[c] = X[c].fillna(v)
    return X.to_numpy(float)


def engine_scores(df):
    eng = TwoStageEngine(intents=REAL_INTENTS)
    out = []
    for r in df.to_dict("records"):
        f = {k: r.get(k) for k in BASE_FEATS}
        f["added_to_cart"] = r.get("added_to_cart")
        f["views_before_first_commercial"] = r.get("views_before_first_commercial")
        inf = eng.score_aggregates(f)
        out.append(TIER[inf.intent] * 10 + inf.confidence)
    return np.array(out)


def capture(scores, purchased, rng):
    order = np.lexsort((rng.random(len(scores)), -scores))
    cum = np.cumsum(purchased[order]) / max(1, purchased.sum())
    n = len(scores)
    return {c: cum[min(n - 1, int(c * n) - 1)] * 100 for c in CUTS}


def run_track(name, train, test, lines, rng):
    ytr = train["purchased"].to_numpy(bool)
    yte = test["purchased"].to_numpy(bool)
    Xtr, Xte = matrix(train), matrix(test)

    scaler = StandardScaler().fit(Xtr)
    lr = LogisticRegression(max_iter=1000, random_state=SEED)
    lr.fit(scaler.transform(Xtr), ytr)
    p_lr = lr.predict_proba(scaler.transform(Xte))[:, 1]
    print(f"  {name}: LR done", flush=True)

    gb = HistGradientBoostingClassifier(random_state=SEED, max_iter=200)
    gb.fit(Xtr, ytr)
    p_gb = gb.predict_proba(Xte)[:, 1]
    print(f"  {name}: GBDT done", flush=True)

    s_eng = engine_scores(test)
    print(f"  {name}: engine done", flush=True)

    rows = [("rule engine (intent tiers)", s_eng),
            ("logistic regression", p_lr),
            ("gradient boosting", p_gb)]
    lines.append(f"\n### {name}\n")
    lines.append("| policy | AUC | capture @5% | @10% | @20% |")
    lines.append("|---|---|---|---|---|")
    for label, s in rows:
        cv = capture(s, yte, rng)
        lines.append(f"| {label} | {roc_auc_score(yte, s):.3f} | "
                     + " | ".join(f"{cv[c]:.0f}%" for c in CUTS) + " |")

    coef = sorted(zip(MODEL_FEATS, lr.coef_[0]), key=lambda kv: -abs(kv[1]))
    lines.append("\nLR standardized coefficients (|top 6|): "
                 + ", ".join(f"`{k}` {v:+.2f}" for k, v in coef[:6]))


def main():
    rng = np.random.default_rng(SEED)
    lines = ["# Learned weights vs the rule engine: how big is the headroom?",
             "",
             "Generated by `evaluate_learned.py`. Same censored features, same",
             "temporal splits, same held-out samples as the baseline report.",
             "AUC = purchase ranking power; capture = % of purchases in the",
             "top-X% of traffic under each policy's ranking."]

    print("RetailRocket ...", flush=True)
    rr = pd.read_csv("real_sessions.csv")
    run_track("RetailRocket — train 3.5 months, test final month",
              rr[rr["start_ms"] < SPLIT_MS], rr[rr["start_ms"] >= SPLIT_MS],
              lines, rng)
    del rr

    print("REES46 ...", flush=True)
    cols = (["month", "added_to_cart", "purchased",
             "views_before_first_commercial"] + BASE_FEATS)
    re = pd.read_csv("rees46_sessions.csv", usecols=lambda c: c in cols)
    oct_ = re[re["month"] == "2019-10"]
    nov = re[re["month"] == "2019-11"]
    del re
    run_track(f"REES46 — train Oct ({REES_TRAIN_SAMPLE//10**6}M sample), "
              f"test Nov ({REES_TEST_SAMPLE//10**3}k sample, Black Friday)",
              oct_.sample(n=min(REES_TRAIN_SAMPLE, len(oct_)), random_state=SEED),
              nov.sample(n=min(REES_TEST_SAMPLE, len(nov)), random_state=SEED),
              lines, rng)

    with open("reports/learned-weights-headroom.md", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote reports/learned-weights-headroom.md")


if __name__ == "__main__":
    main()
